version: '3'

networks:
  wordpress_net: #Declarando uma rede
    driver: bridge #Driver mais utilizado para canal de comunicação,existem outros para poder se utilizar

volumes:
  mariadb-vol: {} 
  wordpress_vol: {}

services: #Declarando os conteiners,serviços do compose
  banco:
    restart: always
    container_name: bancodedados
    image: mariadb:${MARIADB_TAG} #Nome da imagem
    networks:
      - wordpress_net #Nome da network
    volumes:
      - mariadb_vol:/var/www/html
    environment: #Variáveis de ambiente
      - MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE: ${DATABASE_DB_NAME}
      - MYSQL_USER: ${DATABADE_USER}
      - MYSQL_PASSWORD: ${DATABASE_PASSWORD}

  site:
    container_name: meusite
    image: wordpress:${WORDPRESS_TAG  }
    networks:
      - wordpress_net
    volumes:
      - wordpress_vol:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - banco
    restart: always #restarta a aplicação caso exista algum erro
    environment:
      WORDPRESS_DB_HOST: db:3386
      WORDPRESS_DB_NAME: ${DATABASE_DB_NAME}
      WORDPRESS_DB_USER: ${DATABASE_USER}
      WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}
     
#ARQUIVO PARAMETRIZADO
#docker-compose up executa o arquivo
#docker-container ls lista os conteiners
#dokcer-compose run nome-do-container executa um container
#docker container exec -it id-do-container /bin/bash entra dentro container
#kill 1 quebra a operação dentro container
#docker-compose run meusite ps -aux 
#docker-compose down